version: '3.7'
services:
    postgres:
        container_name: db-postgres
        image: postgres:10.5
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres-test
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '15432:5432'
        volumes: 
          - postgresdata:/var/lib/postgresql/data
volumes:
  postgresdata: